export { DocumentsPage } from './components/DocumentsPage'
export { ArchivedDocumentsPage } from './components/ArchivedDocumentsPage'
export { DocumentsStoragePage } from './components/DocumentsStoragePage'
export { DocumentsLayout } from './components/DocumentsLayout'
export { DocumentDetailPage } from './pages/DocumentDetailPage'
