-- =============================================================================
-- Employee Portal EP1 — core schema, RPCs, audit, partitions, pg_cron
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. data.employee_portal_tokens
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS data.employee_portal_tokens (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES data.tenants(id) ON DELETE CASCADE,
  employee_id         uuid NOT NULL REFERENCES data.employees(id) ON DELETE CASCADE,

  token_hash          bytea NOT NULL,
  pin_hash            text,
  pin_attempts        smallint NOT NULL DEFAULT 0,
  pin_locked_until    timestamptz,
  session_version     integer NOT NULL DEFAULT 1,
  compromised         boolean NOT NULL DEFAULT false,

  expires_at          timestamptz,
  is_active           boolean NOT NULL DEFAULT true,

  label               text,
  shared_device       boolean NOT NULL DEFAULT false,
  last_accessed_at    timestamptz,

  created_by_user_id  uuid REFERENCES data.profiles(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  revoked_at          timestamptz,
  revoke_reason       text,

  CONSTRAINT employee_portal_tokens_pin_attempts_nonneg
    CHECK (pin_attempts >= 0),
  CONSTRAINT employee_portal_tokens_session_version_positive
    CHECK (session_version > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_portal_tokens_hash
  ON data.employee_portal_tokens (token_hash);

CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_portal_tokens_active_label
  ON data.employee_portal_tokens (employee_id, label)
  WHERE is_active = true
    AND revoked_at IS NULL
    AND expires_at IS NULL
    AND label IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_employee_portal_tokens_employee_active
  ON data.employee_portal_tokens (employee_id, is_active)
  WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_employee_portal_tokens_tenant
  ON data.employee_portal_tokens (tenant_id, created_at DESC);

COMMENT ON TABLE data.employee_portal_tokens IS
  'Tokens d''accés al portal empleat. Només token_hash (SHA-256); el secret mai es persisteix.';
COMMENT ON COLUMN data.employee_portal_tokens.token_hash IS
  'SHA-256 del secret d''URL (/e/{secret}). Generat a capa app abans de la RPC.';
COMMENT ON COLUMN data.employee_portal_tokens.compromised IS
  'Revocació d''emergència: invalida qualsevol JWT existent al següent refresh.';

-- -----------------------------------------------------------------------------
-- 2. data.employee_portal_access_logs (particionada mensualment)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS data.employee_portal_access_logs (
  id              bigint GENERATED BY DEFAULT AS IDENTITY,
  token_id        uuid NOT NULL REFERENCES data.employee_portal_tokens(id) ON DELETE CASCADE,
  employee_id     uuid NOT NULL REFERENCES data.employees(id) ON DELETE CASCADE,
  tenant_id       uuid NOT NULL REFERENCES data.tenants(id) ON DELETE CASCADE,

  accessed_at     timestamptz NOT NULL DEFAULT now(),
  ip_address      inet,
  user_agent      text,

  action          text NOT NULL,
  http_status     smallint,
  failure_reason  text,

  PRIMARY KEY (id, accessed_at),
  CONSTRAINT employee_portal_access_logs_action_check CHECK (action IN (
    'view_schedule',
    'view_history',
    'punch_in',
    'punch_out',
    'pin_failed',
    'token_invalid',
    'token_expired',
    'session_create',
    'session_refresh'
  ))
) PARTITION BY RANGE (accessed_at);

CREATE TABLE IF NOT EXISTS data.employee_portal_access_logs_2026_07
  PARTITION OF data.employee_portal_access_logs
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE TABLE IF NOT EXISTS data.employee_portal_access_logs_2026_08
  PARTITION OF data.employee_portal_access_logs
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE TABLE IF NOT EXISTS data.employee_portal_access_logs_2026_09
  PARTITION OF data.employee_portal_access_logs
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

CREATE TABLE IF NOT EXISTS data.employee_portal_access_logs_default
  PARTITION OF data.employee_portal_access_logs DEFAULT;

CREATE INDEX IF NOT EXISTS idx_epal_token_accessed
  ON data.employee_portal_access_logs (token_id, accessed_at DESC);

CREATE INDEX IF NOT EXISTS idx_epal_employee_accessed
  ON data.employee_portal_access_logs (employee_id, accessed_at DESC);

CREATE INDEX IF NOT EXISTS idx_epal_tenant_accessed
  ON data.employee_portal_access_logs (tenant_id, accessed_at DESC);

COMMENT ON TABLE data.employee_portal_access_logs IS
  'Auditoria d''accés al portal empleat. Particionada per mes; retenció 90 dies.';

CREATE OR REPLACE FUNCTION data.create_employee_portal_access_logs_partition(p_month_start date)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_month_end date := (p_month_start + interval '1 month')::date;
  v_table_name text := 'employee_portal_access_logs_'
    || to_char(p_month_start, 'YYYY_MM');
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'data' AND c.relname = v_table_name
  ) THEN
    EXECUTE format(
      'CREATE TABLE data.%I PARTITION OF data.employee_portal_access_logs FOR VALUES FROM (%L) TO (%L)',
      v_table_name,
      p_month_start,
      v_month_end
    );
  END IF;
END;
$$;

SELECT data.create_employee_portal_access_logs_partition(date_trunc('month', now())::date);
SELECT data.create_employee_portal_access_logs_partition(
  (date_trunc('month', now()) + interval '1 month')::date
);

-- -----------------------------------------------------------------------------
-- 3. time_punches.source = 'portal'
-- -----------------------------------------------------------------------------
ALTER TABLE data.time_punches
  DROP CONSTRAINT IF EXISTS time_punches_source_check;

ALTER TABLE data.time_punches
  ADD CONSTRAINT time_punches_source_check
  CHECK (source IN ('mobile', 'station', 'manual_entry', 'portal'));

-- -----------------------------------------------------------------------------
-- 4. RLS
-- -----------------------------------------------------------------------------
ALTER TABLE data.employee_portal_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE data.employee_portal_access_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "employee_portal_tokens: manager select"
  ON data.employee_portal_tokens FOR SELECT
  USING (
    data.jwt_has_permission(tenant_id, 'attendance.manage')
  );

CREATE POLICY "employee_portal_tokens: manager insert"
  ON data.employee_portal_tokens FOR INSERT
  WITH CHECK (
    data.jwt_has_permission(tenant_id, 'attendance.manage')
  );

CREATE POLICY "employee_portal_tokens: manager update"
  ON data.employee_portal_tokens FOR UPDATE
  USING (
    data.jwt_has_permission(tenant_id, 'attendance.manage')
  )
  WITH CHECK (
    data.jwt_has_permission(tenant_id, 'attendance.manage')
  );

CREATE POLICY "employee_portal_access_logs: manager select"
  ON data.employee_portal_access_logs FOR SELECT
  USING (
    data.jwt_has_permission(tenant_id, 'attendance.manage')
  );

GRANT SELECT, INSERT, UPDATE ON data.employee_portal_tokens TO authenticated;
GRANT SELECT ON data.employee_portal_access_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON data.employee_portal_tokens TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON data.employee_portal_access_logs TO service_role;

-- -----------------------------------------------------------------------------
-- 5. API view (sense token_hash)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW api.employee_portal_tokens
  WITH (security_invoker = true)
AS
  SELECT
    id,
    tenant_id,
    employee_id,
    (pin_hash IS NOT NULL) AS pin_required,
    pin_attempts,
    pin_locked_until,
    session_version,
    compromised,
    expires_at,
    is_active,
    label,
    shared_device,
    last_accessed_at,
    created_by_user_id,
    created_at,
    revoked_at,
    revoke_reason
  FROM data.employee_portal_tokens;

GRANT SELECT ON api.employee_portal_tokens TO authenticated;

-- -----------------------------------------------------------------------------
-- 6. Audit triggers
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION data.trg_audit_employee_portal_tokens()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data
AS $$
DECLARE
  v_site_id uuid;
BEGIN
  SELECT e.site_id INTO v_site_id
  FROM data.employees e
  WHERE e.id = COALESCE(NEW.employee_id, OLD.employee_id);

  IF TG_OP = 'INSERT' THEN
    PERFORM data.log_audit_event(
      NEW.tenant_id,
      COALESCE(auth.uid(), NEW.created_by_user_id),
      v_site_id,
      'EMPLOYEE_PORTAL_TOKEN_CREATED',
      'employee_portal_token',
      NEW.id,
      jsonb_build_object(
        'employee_id', NEW.employee_id,
        'label', NEW.label,
        'shared_device', NEW.shared_device,
        'expires_at', NEW.expires_at,
        'pin_required', (NEW.pin_hash IS NOT NULL)
      )
    );
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
     AND OLD.revoked_at IS NULL
     AND NEW.revoked_at IS NOT NULL THEN
    PERFORM data.log_audit_event(
      NEW.tenant_id,
      auth.uid(),
      v_site_id,
      'EMPLOYEE_PORTAL_TOKEN_REVOKED',
      'employee_portal_token',
      NEW.id,
      jsonb_build_object(
        'employee_id', NEW.employee_id,
        'label', NEW.label,
        'revoke_reason', NEW.revoke_reason,
        'compromised', NEW.compromised,
        'session_version', NEW.session_version
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_audit_employee_portal_tokens ON data.employee_portal_tokens;
CREATE TRIGGER trg_audit_employee_portal_tokens
  AFTER INSERT OR UPDATE ON data.employee_portal_tokens
  FOR EACH ROW EXECUTE FUNCTION data.trg_audit_employee_portal_tokens();

-- -----------------------------------------------------------------------------
-- 7. RPCs (manager / attendance.manage)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION api.create_employee_portal_token(
  p_employee_id   uuid,
  p_token_hash    bytea,
  p_label         text DEFAULT NULL,
  p_pin_hash      text DEFAULT NULL,
  p_expires_at    timestamptz DEFAULT NULL,
  p_shared_device boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, api, public
AS $$
DECLARE
  v_emp record;
  v_token_id uuid;
BEGIN
  IF p_token_hash IS NULL OR length(p_token_hash) = 0 THEN
    RAISE EXCEPTION 'invalid_token_hash' USING ERRCODE = 'check_violation';
  END IF;

  SELECT e.id, e.tenant_id, e.site_id, e.status
  INTO v_emp
  FROM data.employees e
  WHERE e.id = p_employee_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'employee_not_found: %', p_employee_id USING ERRCODE = 'no_data_found';
  END IF;

  IF v_emp.status IS DISTINCT FROM 'active' THEN
    RAISE EXCEPTION 'employee_not_active' USING ERRCODE = 'check_violation';
  END IF;

  IF NOT data.jwt_has_permission(v_emp.tenant_id, 'attendance.manage', v_emp.site_id) THEN
    RAISE EXCEPTION 'insufficient_privilege: attendance.manage required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  INSERT INTO data.employee_portal_tokens (
    tenant_id,
    employee_id,
    token_hash,
    pin_hash,
    expires_at,
    label,
    shared_device,
    created_by_user_id
  ) VALUES (
    v_emp.tenant_id,
    v_emp.id,
    p_token_hash,
    p_pin_hash,
    p_expires_at,
    NULLIF(btrim(p_label), ''),
    COALESCE(p_shared_device, false),
    auth.uid()
  )
  RETURNING id INTO v_token_id;

  RETURN jsonb_build_object('token_id', v_token_id);
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'duplicate_active_label'
      USING ERRCODE = 'unique_violation',
            DETAIL = 'Ja existeix un token permanent actiu amb aquesta etiqueta per l''empleat.';
END;
$$;

CREATE OR REPLACE FUNCTION api.revoke_employee_portal_token(
  p_token_id     uuid,
  p_reason       text DEFAULT NULL,
  p_compromised  boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, api, public
AS $$
DECLARE
  v_token record;
BEGIN
  SELECT t.id, t.tenant_id, t.employee_id, t.is_active, t.revoked_at, t.session_version
  INTO v_token
  FROM data.employee_portal_tokens t
  WHERE t.id = p_token_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'token_not_found: %', p_token_id USING ERRCODE = 'no_data_found';
  END IF;

  IF NOT data.jwt_has_permission(v_token.tenant_id, 'attendance.manage') THEN
    RAISE EXCEPTION 'insufficient_privilege: attendance.manage required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_token.revoked_at IS NOT NULL OR NOT v_token.is_active THEN
    RETURN jsonb_build_object(
      'token_id', v_token.id,
      'already_revoked', true,
      'session_version', v_token.session_version
    );
  END IF;

  UPDATE data.employee_portal_tokens
  SET
    is_active = false,
    revoked_at = now(),
    revoke_reason = NULLIF(btrim(p_reason), ''),
    compromised = COALESCE(p_compromised, false),
    session_version = session_version + 1
  WHERE id = p_token_id
  RETURNING session_version INTO v_token.session_version;

  RETURN jsonb_build_object(
    'token_id', p_token_id,
    'revoked', true,
    'session_version', v_token.session_version,
    'compromised', COALESCE(p_compromised, false)
  );
END;
$$;

CREATE OR REPLACE FUNCTION api.list_employee_portal_tokens(p_employee_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, api, public
AS $$
DECLARE
  v_emp record;
  v_rows jsonb;
BEGIN
  SELECT e.id, e.tenant_id, e.site_id
  INTO v_emp
  FROM data.employees e
  WHERE e.id = p_employee_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'employee_not_found: %', p_employee_id USING ERRCODE = 'no_data_found';
  END IF;

  IF NOT data.jwt_has_permission(v_emp.tenant_id, 'attendance.manage', v_emp.site_id) THEN
    RAISE EXCEPTION 'insufficient_privilege: attendance.manage required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT COALESCE(jsonb_agg(row_to_json(t)::jsonb ORDER BY t.created_at DESC), '[]'::jsonb)
  INTO v_rows
  FROM api.employee_portal_tokens t
  WHERE t.employee_id = p_employee_id;

  RETURN v_rows;
END;
$$;

CREATE OR REPLACE FUNCTION api.list_employee_portal_access_logs(
  p_token_id uuid,
  p_limit    integer DEFAULT 50
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, api, public
AS $$
DECLARE
  v_token record;
  v_rows jsonb;
  v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 50), 1), 200);
BEGIN
  SELECT t.id, t.tenant_id, t.employee_id
  INTO v_token
  FROM data.employee_portal_tokens t
  WHERE t.id = p_token_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'token_not_found: %', p_token_id USING ERRCODE = 'no_data_found';
  END IF;

  IF NOT data.jwt_has_permission(v_token.tenant_id, 'attendance.manage') THEN
    RAISE EXCEPTION 'insufficient_privilege: attendance.manage required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT COALESCE(jsonb_agg(row_to_json(l)::jsonb ORDER BY l.accessed_at DESC), '[]'::jsonb)
  INTO v_rows
  FROM (
    SELECT
      l.id,
      l.token_id,
      l.employee_id,
      l.tenant_id,
      l.accessed_at,
      l.ip_address::text AS ip_address,
      l.user_agent,
      l.action,
      l.http_status,
      l.failure_reason
    FROM data.employee_portal_access_logs l
    WHERE l.token_id = p_token_id
    ORDER BY l.accessed_at DESC
    LIMIT v_limit
  ) l;

  RETURN v_rows;
END;
$$;

GRANT EXECUTE ON FUNCTION api.create_employee_portal_token(uuid, bytea, text, text, timestamptz, boolean)
  TO authenticated;
GRANT EXECUTE ON FUNCTION api.revoke_employee_portal_token(uuid, text, boolean)
  TO authenticated;
GRANT EXECUTE ON FUNCTION api.list_employee_portal_tokens(uuid)
  TO authenticated;
GRANT EXECUTE ON FUNCTION api.list_employee_portal_access_logs(uuid, integer)
  TO authenticated;

-- -----------------------------------------------------------------------------
-- 8. Maintenance (pg_cron)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION data.deactivate_expired_employee_portal_tokens()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, public
AS $$
DECLARE
  v_count integer;
BEGIN
  UPDATE data.employee_portal_tokens
  SET
    is_active = false,
    session_version = session_version + 1
  WHERE is_active = true
    AND expires_at IS NOT NULL
    AND expires_at < now()
    AND revoked_at IS NULL;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION data.cleanup_employee_portal_access_logs(p_retention_days integer DEFAULT 90)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, public
AS $$
DECLARE
  v_count integer;
BEGIN
  DELETE FROM data.employee_portal_access_logs
  WHERE accessed_at < now() - make_interval(days => GREATEST(p_retention_days, 1));

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

DO $$
DECLARE
  v_job_id bigint;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    SELECT jobid INTO v_job_id
    FROM cron.job
    WHERE jobname = 'deactivate-expired-employee-portal-tokens'
    LIMIT 1;
    IF v_job_id IS NOT NULL THEN
      PERFORM cron.unschedule(v_job_id);
    END IF;
    PERFORM cron.schedule(
      'deactivate-expired-employee-portal-tokens',
      '15 3 * * *',
      'SELECT data.deactivate_expired_employee_portal_tokens();'
    );

    SELECT jobid INTO v_job_id
    FROM cron.job
    WHERE jobname = 'cleanup-employee-portal-access-logs'
    LIMIT 1;
    IF v_job_id IS NOT NULL THEN
      PERFORM cron.unschedule(v_job_id);
    END IF;
    PERFORM cron.schedule(
      'cleanup-employee-portal-access-logs',
      '30 4 * * 0',
      'SELECT data.cleanup_employee_portal_access_logs(90);'
    );
  END IF;
END;
$$;

NOTIFY pgrst, 'reload schema';
